title: "Justin Taylor" # the name of your site, e.g. ACME Corp.

# Name of the author
author: Justin Taylor

# Short bio or description (displayed in the header)
description: Hang on, let me write that down

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/avatar.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: hello@sjustintaylor.me
  facebook:
  flickr:
  github: sjustintaylor
  instagram:
  linkedin: shaun-j-taylor
  pinterest:
  rss: rss
  twitter:
  stackoverflow:
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:
  mastodon: # <your-mastodon-instance>/@<your-user-name> eg. fosstodon.org/@username

url: "https://sjustintaylor.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

# Site config, don't need to touch
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

permalink: /:title/

include: ["_pages"]

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Taskfile.yml
