# Site settings
title:          Justin Taylor
description:    "I write occasionally"
url:            "https://sjustintaylor.github.io"

# Google Analytics
google_analytics: UA-75405424-1

# Author
author:
  name:         Justin Taylor
  url:          https://www.sjustintaylor.com.au
  email:        s.justin.taylor@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
