# https://taskfile.dev

version: '3'

tasks:
  dev:
    cmds:
      - pnpm dev

  build:
    cmds:
      - pnpm run build

  preview:
    cmds:
      - pnpm run preview

  sync:
    cmds:
      - pnpm run sync

  astro:
    cmds:
      - pnpm run astro

  format:check:
    cmds:
      - pnpm run format:check

  format:
    cmds:
      - pnpm run format

  lint:
    cmds:
      - pnpm run lint
